[project]
name = "true-crime"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-openai>=0.3.16",
    "langgraph>=0.4.3",
    "langgraph-cli[inmem]>=0.2.10",
    "loguru>=0.7.3",
    "pydantic>=2.11.4",
    "ruff>=0.11.9",
]
